import { StyleSheet } from 'react-native';

export const colors = {
  page: '#F5F7F0',
  card: '#FFFFFF',
  border: '#DCE5D9',
  divider: '#E4EAE2',
  primary: '#176A46',
  onPrimary: '#FFFFFF',
  heading: '#183B2A',
  text: '#304436',
  muted: '#4B5F51',
  label: '#284A35',
  inputText: '#18291E',
  inputBorder: '#A9BBAC',
  placeholder: '#667569',
  notice: '#E4F0E6',
  noticeText: '#1D4932',
  danger: '#A33829',
  emergency: '#AD382C',
  stop: '#9D412F',
  caution: '#675C46',
  chipBorder: '#B6C4B8',
  link: '#28563B',
};

// Large type and touch targets throughout: the main users are older adults.
export const ui = StyleSheet.create({
  page: { paddingHorizontal: 20, paddingTop: 64, paddingBottom: 48, gap: 16, maxWidth: 700, width: '100%', alignSelf: 'center' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  eyebrow: { color: '#36614B', fontWeight: '800', fontSize: 13, letterSpacing: 1.5 },
  heading: { color: '#163E2B', fontSize: 38, fontWeight: '800', marginTop: -10 },
  intro: { color: '#344B3B', fontSize: 18, lineHeight: 27 },
  card: { backgroundColor: colors.card, borderRadius: 18, padding: 20, gap: 12, borderWidth: 1, borderColor: colors.border },
  sectionTitle: { color: colors.heading, fontSize: 24, fontWeight: '800' },
  helper: { color: colors.muted, fontSize: 16, lineHeight: 24 },
  small: { color: '#56695B', fontSize: 14, lineHeight: 20 },
  label: { color: colors.label, fontSize: 16, fontWeight: '700', marginTop: 6 },
  input: {
    borderWidth: 1.5,
    borderColor: colors.inputBorder,
    borderRadius: 12,
    padding: 14,
    color: colors.inputText,
    fontSize: 18,
    minHeight: 54,
    backgroundColor: colors.card,
  },
  largeInput: { minHeight: 118, textAlignVertical: 'top' },
  notice: { color: colors.noticeText, fontSize: 16, lineHeight: 22, backgroundColor: colors.notice, padding: 14, borderRadius: 10 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  divider: { borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: 12 },
});
